services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  simulation:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
  db:
    image: postgres:15.1-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - rider-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : postgres

volumes:
  rider-db:
    external: true