services:
  app:
    image: app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  db:
    image: postgres:15.1-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : postgres

volumes:
  app-db:
    external: true