services:
  app:
    image: app
    ports:
      - 8080:8080
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : postgres

volumes:
  app-db:
    external: true