name: Go Deploy Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v -o my-app ./...
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: built-app
          path: ./built-app
      - name: Deploy to render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api -key: ${{ secrets.RENDER_TOKEN }}
